Removed System.out command from parsePluginYamlFileTest
jenkinsci/plugin-installation-manager-tool pull request #150
Opened 2020-07-26 15:52 UTC by mikepain

#103 & #122 as discussed with @timja I have created a new pull request with the one line of code removed

2020-07-27 19:26 UTC, timja commented on plugin-management-library/src/main/java/io/jenkins/tools/pluginmanager/impl/PluginManager.java
> +        if ((refDir == null) ||
I think these changes were meant for a different PR?
you should create a new branch for this and create a PR from there

2020-07-27 20:34 UTC, mikepain commented
Sorry

I obviously misunderstand how I should use forks. I thought this change
would be isolated from the work I created a pull request for yesterday .

I thought I could make all changes on the master of that fork. But instead
I should  make all changes on  a branch of that fork.

Is that the correct way to do it?

I will take a branch.

Thanks

Mike



On Mon, 27 Jul 2020 at 20:26, Tim Jacomb <notifications@github.com> wrote:

> *@timja* commented on this pull request.
> ------------------------------
>
> In
> plugin-management-library/src/main/java/io/jenkins/tools/pluginmanager/impl/PluginManager.java
> <https://github.com/jenkinsci/plugin-installation-manager-tool/pull/150#discussion_r461117444>
> :
>
> >      void createRefDir() {
> +
> +        if ((refDir == null) ||
>
> I think these changes were meant for a different PR?
> you should create a new branch for this and create a PR from there
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/jenkinsci/plugin-installation-manager-tool/pull/150#pullrequestreview-456070352>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AGE7Y3OLA2BZ6OPDV67INN3R5XIHVANCNFSM4PIBHMSQ>
> .
>

2020-07-27 20:59 UTC, timja commented
Yes you should never work on the master branch of a fork as you'll hit issues like this.

Create a branch for each pull request.

2020-07-27 21:07 UTC, mikepain commented
Ok understood, I thought as it was my fork I could work on my master I
could commit &  it would be separate from the Jenkins master



On Mon, 27 Jul 2020 at 22:00, Tim Jacomb <notifications@github.com> wrote:

> Yes you should never work on the master branch of a fork as you'll hit
> issues like this.
>
> Create a branch for each pull request.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/jenkinsci/plugin-installation-manager-tool/pull/150#issuecomment-664635590>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AGE7Y3JOXEUXL37WCFF523DR5XTFXANCNFSM4PIBHMSQ>
> .
>

2020-07-28 06:55 UTC, mikepain commented
OK will also remove the changes from my fork master.

2020-07-28 07:12 UTC, jetersen commented
@mikepain perhaps https://lab.github.com/ is a good place to start :)

This doc [creating a pull request from a fork](https://docs.github.com/en/github/collaborating-with-issues-and-pull-requests/creating-a-pull-request-from-a-fork) actually mention the word topic branch 👍

2020-07-28 07:21 UTC, mikepain commented
> @mikepain perhaps https://lab.github.com/ is a good place to start :)
> 
> This doc [creating a pull request from a fork](https://docs.github.com/en/github/collaborating-with-issues-and-pull-requests/creating-a-pull-request-from-a-fork) actually mention the word topic branch 👍

Thanks @jetersen

2020-07-28 16:32 UTC, mikepain commented
> > @mikepain perhaps https://lab.github.com/ is a good place to start :)
> > This doc [creating a pull request from a fork](https://docs.github.com/en/github/collaborating-with-issues-and-pull-requests/creating-a-pull-request-from-a-fork) actually mention the word topic branch 👍
> 
> Thanks @jetersen

Thanks @jetersen , as suggested I went through some of the labs & looked at the Github documentation & feel more confident in using Github.

I now understand why the project uses forks, I thought they were instead of branches but I see they should be used as well a branches.

How should I clear up the problem I have created, as my master now contains the fixes for issues #150 & #97?
Should I do the following:

1. Rollback my fork master to the current upstream master
2. Create a fork branch & then fix both issues on that branch
3. Then use on pull request for both issues?

Thanks for your help

Mike

2021-12-16 23:47 UTC, MarkEWaite requested changes
This pull request can be closed.  The change that was to be the original purpose has been made.

2022-03-14 03:37 UTC, closed without merging